### ISSUE TITLE
need a good example - simple "exercising" fabfile

### ISSUE THREAD

**Issue by biggers** [specialunderwear/bashyucksyntax#1]
I have tried a lot of things to get your module to work, here's one attempt -- but no go:

```python
from __future__ import print_function
from requests.exceptions import RequestException

try:
    import bashyucksyntax
    from bashyucksyntax.fakeric import *

    class vagrant_settings(object):
        def __init__(self, vagrant_dict):
            self.vg_dict = vagrant_dict

        def __enter__(self):
            print("vagrant context:")
            pprint(self.vg_dict)

        __call__ = __enter__

        def __exit__(self, type, value, traceback):
            return 0

except ImportError as e:
    print(e)
    from fabric.api import env, hosts, task
    from fabric.context_managers import settings, hide
    from fabric.operations import local, run, sudo
    from fabric.utils import abort
    from fabtools.vagrant import vagrant_settings
```

Please advise as to how to make "dryfab" work, thanks!

**Comment by specialunderwear** [comment]
Ok so when you install this package, the same way you installed fabric, you get a command called dryfab in your path, just like you get a command called fab in your path when you install fabric. Use that command (dryfab) where you would normally use fab.

**Comment by biggers** [comment]
Doh, yes.  Thank you.  I have made some changes already, will get them to you after more additions and cleanup.   Good work.

**Comment by specialunderwear** [comment]
Hi I would love to see your changes.
